name: mirror_fly_demo
version: 2.3.3+26
build_release_date: Mar 10
publish_to: none
description: A MirrorFly Flutter Sample Application.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  file_picker: ^5.2.0+1 #file picker
  fluttertoast: ^8.0.7 #toast
  intl: ^0.17.0 #datetime
  package_info_plus: ^2.0.0 #package info
  image_picker: ^0.8.6
  flutter_profile_picture: ^2.0.0
  permission_handler: ^10.2.0
  emoji_picker_flutter: ^1.4.0
  image_cropping: ^0.0.13 #crop image
  path_provider: ^2.0.11 #path provider
  video_player: ^2.4.7
  lottie: ^1.4.3
  url_launcher: ^6.1.6 #url Launcher
  custom_image_crop: ^0.0.4 #crop image
  photo_view: ^0.14.0
  fluttercontactpicker: ^4.7.0
  audioplayers: ^0.20.1
  contacts_service: ^0.6.3
  google_maps_flutter: ^2.2.1 #google map
  geolocator: ^9.0.2 #geolocator
  geocoding: ^2.0.5 #geocoder for address
  focus_detector: ^2.0.1 #focus detector
  record: ^3.0.0
  swipe_to: ^1.0.2
  flutter_cache_manager: ^3.3.0
  flutter_keyboard_visibility: ^5.4.0
  keyboard_dismisser: ^3.0.0
  scrollable_positioned_list: ^0.3.5 #scrollable position
  otp_text_field: ^1.1.3 #otp field
  firebase_core: ^2.3.0 #firebase core
  firebase_auth: ^4.1.4 #firebas authentication
  firebase_app_installations: ^0.2.1+5 #firebase installations
  firebase_messaging: ^14.1.2 #firebase messaging
  flutter_switch: ^0.3.2 #switchbox
  marquee: ^2.2.0 # marquee text
  qr_code_scanner: ^1.0.1 #qr scanner
  yaml: ^3.1.1
  path: ^1.8.2
  camera: ^0.10.0+4
  better_video_player: ^1.2.8
  internet_connection_checker: ^1.0.0+1 # connectivity check
  provider: ^6.0.3
  photo_manager: ^2.5.2
  oktoast: ^3.3.1
  google_cloud_translation: ^0.0.3 # Google Translator
  grouped_list: ^5.1.2
  share_plus: ^6.3.0
  flutter_inappwebview: ^5.7.2+3 # inapp webview
  flutter_local_notifications: ^13.0.0
  flutter_libphonenumber: ^1.4.0
  open_file_plus: ^3.4.0
  is_lock_screen: ^2.0.0
  mirrorfly_plugin: ^0.0.1
#  mirrorfly_plugin:
#    path: ../mirrorfly_plugin
#    git:
#      url: https://github.com/MirrorFly/MirrorFly-Flutter-plugin.git
#      ref: develop
#  flysdk:
#    path: packages/flysdk


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/countries.txt
    - assets/languages.txt
    - assets/logos/
    - assets/animation/
    - pubspec.yaml

  fonts:
    - family: sf_ui
      fonts:
        - asset: fonts/sf_ui_display_regular.otf
          weight: 400
        - asset: fonts/sf_ui_display_bold.otf
          weight: 700
        - asset: fonts/sf_ui_display_light.otf
          weight: 100
        - asset: fonts/sf_ui_display_medium.otf
          weight: 500
        - asset: fonts/sf_ui_display_semi_bold.otf
          weight: 600
        - asset: fonts/sf_ui_display_thin.otf
          weight: 200




